version: 2.1 
 
executors: 
  conda-executor: 
    docker: 
      - image: continuumio/miniconda3 
 
jobs: 
  build: 
    executor: conda-executor 
    steps: 
      - checkout 
      - run: 
          name: Install Conda Build 
          command: conda install conda-build awscli -c conda-forge 
      - run: 
          name: Build Conda Package 
          command: conda build conda-recipe --output-folder /tmp/conda-bld 
      - run:
          name: Upload to Another Git Repo
          command: |
            PACKAGE_PATH=$(conda build . --output)
            git clone git@github.com:surendra2/conda-store.git
            cd conda-store
            git checkout -b packages
            cp ${PACKAGE_PATH} .
            git add .
            git commit -m "Add new Conda package"
            git push origin packages 
      - run: 
          name: Clean up 
          command: conda clean --all --yes 
 
workflows: 
  version: 2 
  build_and_upload: 
    jobs: 
      - build
