version: 2.1 
 
executors: 
  conda-executor: 
    docker: 
      - image: continuumio/miniconda3 
 
jobs: 
  build: 
    executor: conda-executor 
    steps: 
      - checkout 
      - run: 
          name: Install Conda Build 
          command: conda install conda-build awscli -c conda-forge 
      - run: 
          name: Build Conda Package 
          command: conda build conda-recipe --output-folder /tmp/conda-bld 
      - run:
          name: Upload to Another Git Repo
          command: |
            # Find the package path
            PACKAGE_PATH=$(ls /tmp/conda-bld | grep '.tar.bz2' | head -n 1)
            echo "Found package: ${PACKAGE_PATH}"
            if [ -z "$PACKAGE_PATH" ]; then
              echo "No package file found, aborting."
              exit 1
            fi
            # Clone the repository
            git clone git@github.com:surendra2/conda-store.git
            cd conda-store
            # Create a new branch or checkout existing one
            git checkout -b packages || git checkout packages
            # Copy the package to the repo
            cp /tmp/conda-bld/${PACKAGE_PATH} .
            git add ${PACKAGE_PATH}
            git commit -m "Add new Conda package ${PACKAGE_PATH}"
            git push origin packages

      - run: 
          name: Clean up 
          command: conda clean --all --yes 
 
workflows: 
  version: 2 
  build_and_upload: 
    jobs: 
      - build
